# Generated by Django 4.1.3 on 2024-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='body',
            field=models.TextField(max_length=10024),
        ),
    ]
