# Generated by Django 4.1.3 on 2024-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_diary_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
