# Generated by Django 5.0.1 on 2024-01-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_diary_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-created']},
        ),
    ]
