# Generated by Django 5.0.1 on 2024-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_diary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='color',
            field=models.CharField(default='white', max_length=128),
        ),
    ]
