# Generated by Django 5.0.1 on 2024-01-23 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_diary_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
