# Generated by Django 5.0.1 on 2024-01-23 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_diary_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 5, 29, 5, 901242, tzinfo=datetime.timezone.utc)),
        ),
    ]
