# Generated by Django 5.0.1 on 2024-01-23 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_diary_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='color',
        ),
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
