# Generated by Django 5.0.1 on 2024-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_diary_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
