# Generated by Django 5.0.1 on 2024-01-23 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_diary_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
        ),
    ]
