# Generated by Django 5.0.1 on 2024-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_color_diary_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='diary',
            name='order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
