# Generated by Django 5.0.1 on 2024-01-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_diary_options_diary_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['order']},
        ),
    ]
